### ISSUE TITLE
Bug: Performance issues since v14.5

### ISSUE THREAD

**Issue by pascal-puetz** [help-me-mom/ng-mocks#5255] opened 2023-03-21 15:58 UTC
### Description of the bug

Since we upgraded ng-mocks from version 14.4.0 in our project, our Unit Tests are 3x slower than before. We narrowed the performance degradation down to either v14.5.0 or v14.5.1 (we couldn't get 14.5.0 working without errors). 

This is quite an issue for us, since our Unit Test Suite in said project contains ~7k Tests which used to run in 20-60 seconds depending on the machine. These now take 1-3 minutes.

### An example of the bug

I'm unsure on how I can demonstrate this as I'm not allowed to share the project as-is. I'm pretty sure though you can take any project, up-/downgrade ng-mocks between v14.4.0 and v14.5.1 and notice a severe performance impact.

Link:

### Expected vs actual behavior

No performance degradation compared to v14.4.0.

**Comment by satanTime** [comment] 2023-03-26 12:17
Hi @pascal-puetz,

thank you for the report.

Could you check how it works with the latest version?
If it's still bad.

Could you record CPU profiler during the test execution and share it with me?

**Comment by satanTime** [comment] 2023-06-11 15:12
Closing due to silence. Feel free to reopen it with the requested info or steps how to reproduce.

Thank you in advance.

**Closed by satanTime** 2023-06-11 15:12 UTC
Labels: bug
